# Generated by Django 4.1.4 on 2023-01-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.IntegerField(default=0)),
                ('issue_date', models.DateField()),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.author')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
            ],
        ),
    ]
