# Generated by Django 4.1.4 on 2023-01-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library_app.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.book'),
        ),
    ]
